language: node_js
node_js: 
- 12.16.3
install: npm install
script: gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: 'reactiontimeapp.com'
  skip_cleanup: true
  acl: public_read
  local_dir: public
  region: us-west-1